"""New Client fields

Revision ID: 467dc8aa73b2
Revises: a3389969a93a
Create Date: 2023-11-19 17:57:17.088185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '467dc8aa73b2'
down_revision: Union[str, None] = 'a3389969a93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'dt_inclusao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('client', sa.Column('dt_inclusao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client', sa.Column('dt_alteracao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'dt_alteracao')
    op.drop_column('client', 'dt_inclusao')
    op.alter_column('category', 'dt_inclusao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
