"""Initial

Revision ID: a3389969a93a
Revises: 564267204bec
Create Date: 2023-11-17 23:50:33.535398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3389969a93a'
down_revision: Union[str, None] = '564267204bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('code', sa.String(length=36), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
